##' Takes one of more \code{GRanges} instances as input, converts them
##' to \code{AnnotationTrack} or \code{GeneRegionTrack} objects from
##' the \code{Gviz} package and produces the corresponding plot. The
##' \code{genome} argument controls whether additional ideogram and
##' axis tracks are to be plotted.
##'
##' See \code{\link{pmapToGenome}} for example code.
##' 
##' @title Plot gene region and annotation tracks
##' @param x A \code{Granges} object containing peptides genomics
##' coordinates, typically generated by
##' \code{\link{pmapToGenome}}. These ranges are converted to a
##' \code{AnnotationTrack}.
##' @param ... One or more \code{GRanges} instances, typically
##' resulting from calling \code{\link{etrid2grl}}. These ranges are
##' converted to \code{GeneRegionTrack} instances.
##' @param genome A \code{character} of length 1, giving the name of
##' the genome. Default is \code{"hg38"}. If \code{NULL}, no
##' chromosome and axis tracks are displayed.
##' @param plot A \code{logical} defining if the figure should be
##' plotted. Default is \code{TRUE}.
##' @return Used for its plotting side effects. Invisible returns a
##' list of tracks.
##' @author Laurent Gatto
##' @aliases plotAsGeneRegionTrack
plotAsAnnotationTrack <- function(x, ..., genome = "hg38",
                                  plot = TRUE) {
    stopifnot(is(x, "GRanges"))
    args <- plotAsGeneRegionTrack(..., genome = genome, plot=FALSE)
    pepTrack <- AnnotationTrack(start = start(x),
                                end = end(x),
                                chr = rtracklayer::chrom(x),
                                strand = strand(x),
                                group = mcols(x)$group,
                                id = mcols(x)$pepseq,
                                fill = ifelse(mcols(x)$exonJunctions,
                                    "red", "steelblue"),
                                col = NULL,
                                name = "peptides")
    args <- c(args, pepTrack)
    if (plot) plotTracks(args, groupAnnotation = "id")
    invisible(args)
}

##' @rdname plotAsAnnotationTrack
plotAsGeneRegionTrack <- function(..., genome = "hg38",
                                  plot = TRUE) {
    args <- pairlist(...)
    stopifnot(sapply(args, is, "GRanges"))
    args <- lapply(args, GeneRegionTrack)
    if (!is.null(genome)) {
        chr <- as.character(seqnames(args[[1]])[1])
        ideoTrack <- IdeogramTrack(genome = genome,
                                   chromosome = chr)
        axisTrack <- GenomeAxisTrack()
        args <- c(ideoTrack, axisTrack, args)
        if (plot) plotTracks(args, add53 = TRUE, add35 = TRUE)
    } else {
        if (plot) plotTracks(args)
    }
    invisible(args)
}
